### ISSUE TITLE
Update ETH Mainnet, Ropsten, Rinkeby, Goerli to Berlin (1.10.1)

### ISSUE THREAD

**Issue by mokn** [pokt-foundation/process#39]
### In 2-4 sentences write a self-contained summary of idea and benefits.
One of our main users, EthersJS, is updating their SDK to [Berlin upgrade](https://blog.ethereum.org/2021/03/08/ethereum-berlin-upgrade-announcement/). This is a breaking change to some providers and our current testnet and mainnet nodes are not yet supporting it.
### In 2-4 sentences describe the problem the user faces that this idea addresses.
Currently EthersJS is receiving "null" for the testnet implementations of the Berlin upgrade. We cannot give service for these testnets until the upgrade has been completed. 
### In 2-4 sentences describe how the propose idea address' these pain points.
Follow the documentation in the following link - https://blog.ethereum.org/2021/03/08/ethereum-berlin-upgrade-announcement/
### In 2-3 sentences describe how someone would get started using this.
Existing users would see no change. This only affects products like SDKs who plan to support Berlin, like EthersJS
(If this is baked into an exisiting product, describe this)

### Write a quote here that you would answer to someone asking, that describes why they like the feature release. Would be used as a snippet in Public Relations.
"Pocket now supports the Berlin upgrade!"

### Write a hypothetical customer quote about why they liked this new feature or idea.
"Pocket was extremely quick in supporting these critical Ethereum changes"
### Write a 1-2 sentence call-to-action for how to grab a users attention to this new feature or idea.
"If you want to experience Berlin, come try out endpoints with Pocket"

**Comment by nymd** [comment]
Already done.
